# Generated by Django 2.1.2 on 2019-07-17 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('index', models.IntegerField()),
                ('image_url', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('building', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('level_code', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_code', models.CharField(max_length=20)),
                ('uuid', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=50)),
                ('level_code', models.CharField(max_length=20)),
                ('room_code', models.CharField(max_length=20)),
                ('beacon_type', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=30, max_digits=50)),
                ('longitude', models.DecimalField(decimal_places=30, max_digits=50)),
                ('name', models.CharField(max_length=200)),
                ('speakout', models.CharField(max_length=200)),
                ('m_power', models.IntegerField()),
                ('searchable', models.IntegerField()),
                ('building_id', models.CharField(max_length=50)),
                ('building_name', models.CharField(max_length=100)),
                ('room_name', models.CharField(max_length=100)),
                ('indoor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('building_id', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingFloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_code', models.CharField(max_length=10)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Building')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingFloorPlanBoundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_id', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('sequence', models.IntegerField()),
                ('buildingfloorplan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.BuildingFloorPlan')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_code', models.CharField(max_length=10)),
                ('abbreviation', models.CharField(max_length=10)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Building')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('level_code', models.CharField(default='', max_length=10)),
                ('captured_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('from_node', models.CharField(default='', max_length=20)),
                ('to_node', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
                ('level', models.CharField(default='', max_length=100)),
                ('weight', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(default='', max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('level_code', models.CharField(max_length=50)),
                ('staff', models.CharField(default='', max_length=5)),
                ('interest_type', models.IntegerField()),
                ('building_name', models.CharField(max_length=100)),
                ('map_scale', models.IntegerField()),
                ('parking_field', models.BooleanField()),
                ('visitor', models.BooleanField(default=False)),
                ('descriptions_title', models.CharField(default='', max_length=1000)),
                ('descriptions_text', models.CharField(default='', max_length=2000)),
                ('website', models.CharField(default='', max_length=200)),
                ('opening_text', models.CharField(default='', max_length=200)),
                ('tel', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=200)),
                ('poi_type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PoiImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Poi')),
            ],
        ),
        migrations.CreateModel(
            name='PoiOpeningDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=200)),
                ('days', models.CharField(max_length=200)),
                ('hours', models.CharField(max_length=200)),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Poi')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node', models.CharField(default='', max_length=20)),
                ('to_node', models.CharField(default='', max_length=20)),
                ('nodes', models.CharField(default='', max_length=5000)),
                ('edges', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TileBeaconVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DateTimeField()),
                ('tile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.Tile')),
            ],
        ),
        migrations.CreateModel(
            name='TileBuildingVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DateTimeField()),
                ('tile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.Tile')),
            ],
        ),
        migrations.CreateModel(
            name='TilePoiVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DateTimeField()),
                ('tile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.Tile')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('generated_time', models.DateTimeField()),
                ('expired_time', models.DateTimeField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='', max_length=100, unique=True)),
                ('device_platform', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField()),
                ('active_code', models.CharField(default='', max_length=10)),
                ('current_latitude', models.CharField(default='', max_length=100)),
                ('current_longitude', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='poi',
            name='tile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.Tile'),
        ),
        migrations.AddField(
            model_name='devicecoordinate',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.UserDevice'),
        ),
        migrations.AddField(
            model_name='building',
            name='tile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.Tile'),
        ),
        migrations.AddField(
            model_name='beacon',
            name='tile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.Tile'),
        ),
    ]
